name: PR Check
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use .nvmrc
        uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Format
        run: npm run format
      - name: Typecheck
        run: npm run typecheck
      - name: Check Dependencies
        run: npm run check-dependencies
      - name: Unit Tests
        run: npm run test
      - name: Generate Coverage Report
        run: npm run test-coverage
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
