name: Publish
permissions:
  contents: write
on:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use .nvmrc
        uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Format
        run: npm run format
      - name: Typecheck
        run: npm run typecheck
      - name: Check Dependencies
        run: npm run check-dependencies
      - name: Unit Tests
        run: npm run test
      - name: Generate Coverage Report
        run: npm run test-coverage
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@1a6d90ebcb0e6a6b1d87e37ba693fe453195ae25
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Configure Git User
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Version Packages
        run: npm run lerna version --conventional-commits --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        run: npm run lerna publish from-git --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
